name: tubez
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  google_fonts: ^2.0.0
  font_awesome_flutter: ^10.4.0
  cupertino_icons: ^1.0.2
  url_launcher: ^6.1.6
  google_nav_bar: ^5.0.6
  get: ^4.6.6

dev_dependencies:
  camera: ^0.10.5+2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mobile_scanner: ^3.2.0 # scan QR code
  path_provider: ^2.0.15 # provide path to save file
  qr_flutter: ^4.1.0 # generate qr code
  carousel_slider: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/deadpool.jpg
    - assets/images/elemental.jpg
    - assets/images/transformers.jpg
    - assets/images/the_boys.jpg
    - assets/images/spiderman.jpg

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
        - asset: fonts/Poppins-Light.ttf
        - asset: fonts/Poppins-Medium.ttf
        - asset: fonts/Poppins-Regular.ttf
        - asset: fonts/Poppins-SemiBold.ttf
